source "https://rubygems.org"
gem "jekyll", git: "https://github.com/jekyll/jekyll" 
# group :jekyll_plugins do 
#     gem 'jekyll-picture-tag', git: 'https://github.com/robwierzbowski/jekyll-picture-tag/'
# end
gemspec